#! /bin/bash

function remedy() {
    local file=$1

    local name=$(basename $file| awk -F'.' '{ print $1 }')
    local min=$(echo $name | awk -F '-' '{ print $1 }')
    local max=$(echo $name | awk -F '-' '{ print $2 }')

    [ -z "$min" ] && echo "bad file" && exit 1
    [ -z "$max" ] && echo "bad file" && exit 1

    local num=$(wc -l $file| awk '{ print $1 }')
    sed -n "2,${num}p" $file > /tmp/$name

    while read line
    do
        x=$(echo $line | awk -F, '{ print $1 }')
        [ -z "$x" ] && break

        if [ $x -ge $min -a $x -le $max ]; then
            echo $line >> /tmp/$name
        fi
    done < userdata.txt

    sort -u -t, -V /tmp/$name > /tmp/$name.csv
    sed -i '1ix,y,level,type' /tmp/$name.csv
    mv /tmp/$name.csv $file
    git diff $file
}


#sed -i '/coordinates for x/,/coordinates for x/d' README.md

#for file in result/*.csv
#do
#    name=$(basename $file| awk -F'.' '{ print $1 }')
#    min=$(echo $name | awk -F '-' '{ print $1 }')
#    max=$(echo $name | awk -F '-' '{ print $2 }')

#    remedy $file

#    num=$(wc -l $file| awk '{ print $1 }')
#    num=$(($num-1))

#    printf "\n%-3s coordinates for x from %3s to %3s:  [here]($file)\n" $num $min $max >> README.md
#done


column=0
echo "|x|count|x|count|x|count" >> README.md
echo "|----|----|----|----|----|----" >> README.md

for file in result/*.csv
do
    name=$(basename $file| awk -F'.' '{ print $1 }')
    min=$(echo $name | awk -F '-' '{ print $1 }')
    max=$(echo $name | awk -F '-' '{ print $2 }')

    remedy $file

    num=$(wc -l $file| awk '{ print $1 }')
    num=$(($num-1))

    #printf "\n%-3s coordinates for x from %3s to %3s:  [here]($file)\n" $num $min $max >> README.md

    column=$(($column+1))
    if [ $column -lt 3 ]; then
        echo -n "|[$name]($file)|$num" >> README.md
    else
        column=0
        echo "|[$name]($file)|$num" >> README.md
    fi
done
echo -e '\n--------'>> README.md
